#include "MyApp.h"
#include <string>
#include <iostream>

#if defined(UL_EMBED_FILES)
#endif

#include <Ultralight/platform/Platform.h>
#include "platform/EmbeddedFileSystem.h"
#include <chrono>
#include <thread>
#include <fmt/format.h>
#include <networktables/NetworkTableInstance.h>
#include <networktables/NetworkTable.h>
#include <networktables/DoubleTopic.h>
#include <frc/geometry/Pose2d.h>

#define WINDOW_WIDTH  600
#define WINDOW_HEIGHT 400

MyApp::MyApp() {
#if defined(UL_EMBED_FILES)
  // Use embedded assets if available (generated by embed_files.cmake)
  ultralight::Platform::instance().set_file_system(new ultralight::EmbeddedFileSystem());
#endif
  ///
  /// Create our main App instance.
  ///
  app_ = App::Create();

  ///
  /// Create a resizable window by passing by OR'ing our window flags with
  /// kWindowFlags_Resizable.
  ///
  window_ = Window::Create(app_->main_monitor(), WINDOW_WIDTH, WINDOW_HEIGHT,
    false, kWindowFlags_Titled | kWindowFlags_Resizable);

  ///
  /// Create our HTML overlay-- we don't care about its initial size and
  /// position because it'll be calculated when we call OnResize() below.
  ///
  overlay_ = Overlay::Create(window_, 1, 1, 0, 0);

  ///
  /// Force a call to OnResize to perform size/layout of our overlay.
  ///
  // Avoid calling the virtual OnResize inside the constructor; resize the
  // overlay directly instead.
  overlay_->Resize(window_->width(), window_->height());

  ///
  /// Load a page into our overlay's View
  ///
  overlay_->view()->LoadURL("file:///app.html");

  ///
  /// Register our MyApp instance as an AppListener so we can handle the
  /// App's OnUpdate event below.
  ///
  app_->set_listener(this);

  ///
  /// Register our MyApp instance as a WindowListener so we can handle the
  /// Window's OnResize event below.
  ///
  window_->set_listener(this);

  ///
  /// Register our MyApp instance as a LoadListener so we can handle the
  /// View's OnFinishLoading and OnDOMReady events below.
  ///
  overlay_->view()->set_load_listener(this);

  ///
  /// Register our MyApp instance as a ViewListener so we can handle the
  /// View's OnChangeCursor and OnChangeTitle events below.
  ///
  overlay_->view()->set_view_listener(this);
}

void MyApp::Run() {
  app_->Run();
}

void MyApp::OnUpdate() {
  ///
  /// This is called repeatedly from the application's update loop.
  ///
  /// You should update any app logic here.
  ///


  double time = handler_.getDouble("deltaT");

  frc::Pose2d pose = handler_.getPose2d("robotPose");

  count += time;

  std::string js_code = "updateCounter(" + std::to_string(time) + ");";

  std::cout << "OnUpdate called: counter = " << pose.X().value() << std::endl;

    std::string json = fmt::format(
            R"({{
            "deltaTime": {},
            "pose": {{"x": {}, "y": {}, "rotation": {}}}
        }})",
            count,
            pose.X().value(),
            pose.Y().value(),
            pose.Rotation().Degrees().value()
    );


    std::string script = fmt::format(
            "window.robotData = {}; "
            "window.dispatchEvent(new CustomEvent('robotDataUpdate'));",
            json
    );

    overlay_->view()->EvaluateScript(script.c_str());
}

void MyApp::OnClose(ultralight::Window* window) {
  app_->Quit();
}

void MyApp::OnResize(ultralight::Window* window, uint32_t width, uint32_t height) {
  ///
  /// This is called whenever the window changes size (values in pixels).
  ///
  /// We resize our overlay here to take up the entire window.
  ///
  overlay_->Resize(width, height);
}

void MyApp::OnFinishLoading(ultralight::View* caller,
                            uint64_t frame_id,
                            bool is_main_frame,
                            const String& url) {
  ///
  /// This is called when a frame finishes loading on the page.
  ///
}

void MyApp::OnDOMReady(ultralight::View* caller,
                       uint64_t frame_id,
                       bool is_main_frame,
                       const String& url) {
  ///
  /// This is called when a frame's DOM has finished loading on the page.
  ///
  /// This is the best time to setup any JavaScript bindings.
  ///
  handler_ = NetworkHandler("127.0.0.1");

  handler_.addDoubleSubscriber("deltaT", "drivetrain", "DeltaTime");

  handler_.addPose2dArraySubscriber("robotPoses", "drivetrain", "CurrentPose");
}

void MyApp::OnChangeCursor(ultralight::View* caller,
                           Cursor cursor) {
  ///
  /// This is called whenever the page requests to change the cursor.
  ///
  /// We update the main window's cursor here.
  ///
  window_->SetCursor(cursor);
}

void MyApp::OnChangeTitle(ultralight::View* caller,
                          const String& title) {
  ///
  /// This is called whenever the page requests to change the title.
  ///
  /// We update the main window's title here.
  ///
  window_->SetTitle(title.utf8().data());
}
